apiVersion: apps.kruise.io/v1alpha1
kind: StatefulSet
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    helm.sh/chart: {{ include "guestbook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "guestbook.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "guestbook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  podManagementPolicy: Parallel  # allow parallel updates, works together with maxUnavailable
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      # Do in-place update if possible, currently only image update is supported for in-place update
      podUpdatePolicy: InPlaceIfPossible
      # Allow parallel updates with max number of unavailable instances equals to 2
      maxUnavailable: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "guestbook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      readinessGates:
        # A new condition must be added to ensure the pod remain at NotReady state while the in-place update is happening
      - conditionType: InPlaceUpdateReady 
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-server
          containerPort: {{ .Values.service.port }}
