apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-kruise.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "guestbook-kruise.name" . }}
    helm.sh/chart: {{ include "guestbook-kruise.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http-server
    name: httpserver-port
  - port: {{ .Values.service.sidecarPort }}
    targetPort: sidecar-server
    name: sidecar-port
  selector:
    app.kubernetes.io/name: {{ include "guestbook-kruise.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
